Tested: kernel: 5.7.7, bluez: 5.54-2, xorg-server: 1.20.8

python libraries: python-xlib 0.27, dbus-python 1.2.16

Edit `main.py` and change the `CONTROLLER_MAC` variable in the beginning to your own MAC. You can find the MAC of the bluetooth controller in `bluetoothctl`. E.g. the "5C:87:9C:96:BE:5E" shown in the screenshot below is the MAC.

1. make sure that bluetoothd has the plugin `input` disabled (i.e. "-P input")
2. make sure that bluetooth service is running (systemctl status bluetooth)
3. enter `bluetoothctl` and do `power on`
4. make sure the bluetooth controller is not blocked by software (check rfkill or enable bluetooth in your desktop manager, e.g. gnome)
5. Run `xhost +` to enable root user also draw something on a non-root user's X session. (see [this stackoverflow](https://stackoverflow.com/questions/31902846/how-to-fix-error-xlib-error-displayconnectionerror-cant-connect-to-display-0))
6. Run `sudo python3 main.py`

 
